language: ruby
before_install: gem update --system
bundler_args: --without local_development
rvm:
  - 2.2.9
  - 2.3.6
  - 2.4.3
  - 2.5.0
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
branches:
  only:
    - master
