language: ruby

dist: xenial

cache:
  bundler: true

bundler_args: --without local_development

script: bundle exec rake

jobs:
  include:
    - rvm: 2.5
    - rvm: 2.6
    - rvm: 2.7
    - rvm: ruby-head
    - rvm: 2.7.1
      name: "RuboCop"
      before_install: []
      script: bundle exec rubocop
  allow_failures:
    - rvm: ruby-head

branches:
  only:
    - master
