language: ruby
before_install: gem update --system
bundler_args: --without local_development
rvm:
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - 2.6.0
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
branches:
  only:
    - master
