# This workflow will download a prebuilt Ruby version, install dependencies and
# run RuboCop
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby: [2.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ matrix.ruby }}-${{ hashFiles('**/Gemfile', '**/*.gemspec') }}-${{ github.ref }}
        restore-keys: |
          ${{ runner.os }}-gems-${{ matrix.ruby }}-${{ hashFiles('**/Gemfile', '**/*.gemspec') }}-
          ${{ runner.os }}-gems-${{ matrix.ruby }}-
    - name: Install dependencies
      run: |
        bundle config path vendor/bundle
        bundle install
    - name: Run RuboCop
      run: bundle exec rubocop -P
